// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// test_levmar
void test_levmar();
RcppExport SEXP _levmaR_test_levmar() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_levmar();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_levmaR_test_levmar", (DL_FUNC) &_levmaR_test_levmar, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_levmaR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
